### ISSUE TITLE
ImportError: No module named 'stanfordnlp'

### ISSUE THREAD

**Issue by fooSynaptic** [sogou/SMRCToolkit#12]
the issues i encountered are the module issue.
and i believe the owner should add the stanfordnlp install procedure in the tutorial

**Comment by yxk9810** [comment]
you can find the tutorial about stanfordnlp in  https://github.com/stanfordnlp/stanfordnlp.

**Comment by zhayefei** [comment]
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple stanfordnlp

**Comment by fooSynaptic** [comment]
@zhayefei `ERROR: No matching distribution found for stanfordnlp`
i got setup install issue as same as your propose to run `pip install stanfordnlp`
