### ISSUE TITLE
No module named 'sogou_mrc'的问题

### ISSUE THREAD

**Issue by bigcat2333** [sogou/SMRCToolkit#14]
您好，在运行examples中的文件时出现“No module named 'sogou_mrc'”的错误，但是sogou_mrc下包含__init__.py文件，不知道这个问题是怎么产生的，可以烦请您解答一下么？谢谢！

**Comment by yanchlu** [comment]
你要在根目录（/SMRCToolkit-master$）下运行吧。

**Comment by yanchlu** [comment]
JJX？

**Comment by bigcat2333** [comment]
> 你要在根目录（/SMRCToolkit-master$）下运行吧。

刚刚试了一下还是不行（不知道我理解的对不对）
运行命令是这样的：
(tensorflow) G:\SMRCToolkit-master\examples\run_bidaf>python bidaf_squadv2.py
Traceback (most recent call last):
  File "bidaf_squadv2.py", line 4, in <module>
    from sogou_mrc.data.vocabulary import Vocabulary
ModuleNotFoundError: No module named 'sogou_mrc'
(tensorflow) G:\SMRCToolkit-master>python bidaf_squadv2.py
python: can't open file 'bidaf_squadv2.py': [Errno 2] No such file or directory
(tensorflow) G:\SMRCToolkit-master>python G:\SMRCToolkit-master\examples\run_bidaf\bidaf_squadv2.py
Traceback (most recent call last):
  File "G:\SMRCToolkit-master\examples\run_bidaf\bidaf_squadv2.py", line 4, in <module>
    from sogou_mrc.data.vocabulary import Vocabulary
ModuleNotFoundError: No module named 'sogou_mrc'

**Comment by yanchlu** [comment]
python -m examples.run_bidaf.bidaf_squadv2.py

**Comment by bigcat2333** [comment]
问题解决啦！非常感谢！
