### ISSUE TITLE
NotFoundError: ./vacab.txt

### ISSUE THREAD

**Issue by yanchlu** [sogou/SMRCToolkit#15]
When I run the run_bert_coqa.py,  it comes out an error.
`
tensorflow.python.framework.errors_impl.NotFoundError: ./vocab.txt; No such file or directory
`
I want to know where does this file come from.

**Comment by yanchlu** [comment]
glove.840B.300d.txt?

**Comment by yxk9810** [comment]
vocab.txt  is from bert pretrained model. You can it in https://github.com/google-research/bert.
