### ISSUE TITLE
no 'session' and TypeError

### ISSUE THREAD

**Issue by yanchlu** [sogou/SMRCToolkit#18]
Two questions come up when I run run_bert_coqa.py.
`
Traceback (most recent call last):  
  File "/data2/wangfuyu/NQ/ycl/SMRCToolkit-master/sogou_mrc/model/base_model.py", line 21, in __del__  
    self.session.close()  
AttributeError: 'BertCoQA' object has no attribute 'session'
`

`
 File "/data2/wangfuyu/NQ/ycl/SMRCToolkit-master/examples/run_coqa/run_bert_coqa.py", line 37, in <module>                              
    model = BertCoQA(bert_dir=bert_dir,answer_verificatioin=True)                       
TypeError: __init__() got an unexpected keyword argument 'answer_verificatioin'    
`

The version of my python is 3.6.8 
Could anyone give me some advices?

**Comment by yanchlu** [comment]
By the way, what's the difference between run_bert_coqa.py and run_bert_coqa_base.py?

**Comment by yxk9810** [comment]
run_bert_coqa_base train model based on bert without answer verification. Sorry for misspelling the parameter, it should be answer_verification,

**Comment by yanchlu** [comment]
Thanks a lot.
