### ISSUE TITLE
中文ELMo支持

### ISSUE THREAD

**Issue by watercow** [sogou/SMRCToolkit#2]
如果想实现支持中文的ELMo+BIDAF，是否需要自己封装tf.hub的接口。还是有一些更好的解决方案？

**Comment by yxk9810** [comment]
中文上我们没有进行测试，建议可以在自己使用https://github.com/allenai/bilm-tf 提供的代码在中文上进行训练，另外可以按照ReadMe里面描述的保存字符表示来进行模型加速。
