### ISSUE TITLE
CMRC2018数据集的支持

### ISSUE THREAD

**Issue by MrRace** [sogou/SMRCToolkit#4]
看到examples中有使用BiDAF在CMRC2018数据集上的测试。在`cmrc_bidaf.py`中使用了词向量`embedding_folder`，是否提供该词向量下载地址？谢谢！

**Comment by yxk9810** [comment]
The embedding used in our code can be found in https://github.com/Embedding/Chinese-Word-Vectors

**Comment by MrRace** [comment]
> The embedding used in our code can be found in https://github.com/Embedding/Chinese-Word-Vectors

Thanks!
