### ISSUE TITLE
预处理COQA数据集的问题

### ISSUE THREAD

**Issue by CrownCEO** [sogou/SMRCToolkit#5]
在预处理COQA数据集的时候，我看到到history_question_tokens 是所有历史问题和答案的拼接。
<q> question <a>answer。
在训练集中这样拼接操作应该是正确的。但是在eval验证集中也采用这样的方式感觉并不合适。
因为相当于引入了本来应该未知的数据，在验证集中的answer应该是未知的，不能和question拼接到一起。
希望可以解答我的疑惑，谢谢您。

**Comment by yylun** [comment]
It's ok to use golden answers of previous turns when eval/test

You can find official responses about this topic here https://groups.google.com/forum/#!topic/coqa/fuElNyxgR6U

**Comment by CrownCEO** [comment]
Thanks for your help.
