### ISSUE TITLE
several minor errors of Trainer

### ISSUE THREAD

**Issue by threefoldo** [sogou/SMRCToolkit#6]
This framework is handy, I like it. Here are several problems I found:

1. Trainer._evaluate requires 'model_path', but BaseModel doesn't provide that parameter;

2. Trainer._inference call Trainer.inference (with 3 parameters) which doesn't exists.

Also, the default logging level disable all training information, that's inconvenient. At the end of training, there is no information of training at all.

**Comment by yylun** [comment]
Thanks for pointing out these bugs, 1&2 should be a version problem, will fix that soon

Currently we enable the logging information by adding
```python
logging.getLogger().setLevel(logging.INFO)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
```

**Comment by threefoldo** [comment]
Thanks.
